version: 2

jobs:
  build:
    docker: 
      - image: circleci/node:8.11.3
      
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: npm install
          working_directory: ~/repo
          command: npm install

      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/node_modules
            
      - run:
          name: "Test"
          working_directory: ~/repo/
          command: |
            npm test -- --clearCache
            npm test

